  /*****************************************************************/
  //		    Steganography :-         Version 2.0
  //	      Developed By
  //			 N.C.C.T
  //			 #109, 2nd Floor
  //			 N.H- ROAD
  //			 CHENNAI - 600034
  //        Programmed By
  //			 T.R.Ratheesh
  //                     tr.ratheesh@gmail.com
  /*****************************************************************/
#ifndef    _WIREDEFS_H

#define VIDEO_MEM_SEGMENT (0x10)
#define GRAPH_MODE         (0x2)
#define TRUE                 (1)
#define FALSE                (0)
#define UP_KEY                72
#define DOWN_KEY              80
#define LEFT_KEY              75
#define RIGHT_KEY             77
#define ESC_KEY               27
#define BACK_SPACE  	       8
#define TAB_KEY    	       9
#define ENTER_KEY 	      13
#define INS_KEY    	      82
#define SPACE_KEY   	      32

#define MAXINPUT 	     155
#define MAXLEN                30
#define EDITLEN  	      78
#define DELAY    	   FALSE
#define WAIT     	    TRUE

#define BS 		       8
#define FORMFEED 	      12
#define CR 		      13
#define ESC  		      27
#define HOMEKEY 	     327
#define ENDKEY 		     335
#define UPKEY 		     328
#define DOWNKEY 	     336
#define PGUPKEY 	     329
#define PGDNKEY 	     337
#define LEFTKEY 	     331
#define INSKEY 		     338
#define RIGHTKEY 	     333
#define DELKEY               339
#define CTRLLEFTKEY          371
#define CTRLRIGHTKEY         372
#define F1                   315
#define F2                   316
#define F3                   317
#define F4 		     318
#define F5 		     319
#define F6 		     320
#define F7 		     321
#define F8 		     322
#define F9 		     323
#define F10 		     324
#define ALT_F                 33

typedef unsigned int UINT16;
typedef unsigned long  UINT32;
typedef unsigned char UCHAR;
typedef const char CCHAR;
typedef unsigned int COLOR;
typedef int BOOL;
typedef double DOB16;
typedef void *BUFFER;

#define   _WIREDEFS_H
#endif


